# Generated by Django 3.0.6 on 2020-05-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nameE', models.CharField(max_length=100)),
                ('telefonoE', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
    ]
