# Generated by Django 3.0.6 on 2020-05-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGBD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('Tipoalimentacion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'alimentacion',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameA', models.CharField(max_length=100)),
                ('medio', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'animal',
            },
        ),
    ]
