# Generated by Django 3.0.6 on 2020-05-27 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGBD', '0002_alimentacion_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='alimentacion',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='SGBD.Alimentacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SGBD.Empleado'),
            preserve_default=False,
        ),
    ]
